<a href="https://colab.research.google.com/github/JorgeGalarza777/SIM_YAC_GALARZA_UPSE2023/blob/main/TAREASIMULACI%C3%93N2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Hola mundo

**TAREA DE ECUACIÓN DE LA DIFUSIVIDAD**

**EVALUACIÓN DE LA ECUACIÓN DE LA DIFUSIVIDAD EN FUNCIÓN DE LA PRESIÓN CON 5 CELDAS Y UN DT=10000 DÍAS**

In [ ]:
import numpy as np
L=1000 #distancia total
dx=200 #deltax
Distance=np.arange(0,L+1,dx) #Crear un vector de las distancias
P01=np.ones_like(Distance)
print (P01)

[1 1 1 1 1 1]


In [ ]:
PYac=4000
PFrontd=0 #Frontera Derecha
PFronti=0 #Frontera Izquierda
Tiempo=550000
DT=10000
Pdt=np.zeros_like(Distance)

In [ ]:
P01=np.ones_like(Distance)
P01=P01*PYac
P01[0]=PFronti
P01[len(P01)-1]=PFrontd
P0in=P01 #Condicion inicial
Pdt=P01 #Vector de resultados DT
t=DT #Primera interaccion

In [ ]:
print (P01)

[   0 4000 4000 4000 4000    0]


In [ ]:
def Presdt(P1,P2,P3,deltat,deltax):
  return(((P1-2*P2+P3)/(deltax*deltax))*deltat)+P2

In [ ]:
while t<Tiempo:
    for i in range(0,len(P0in)-1):
      if i==0:
        Pdt[i]=P0in[0]
      elif i==len(P0in)-1:
        Pdt[i]=P0in[len(P0in)-1]
      else:
        Pdt[i]=Presdt(P0in[i-1],P0in[i],P0in[i+1],DT,dx)
    t=t+DT
    P0in=Pdt
    P01=np.append(P01,Pdt)

In [ ]:
print (P01)

[   0 3000 3750 3937 2984    0    0 3000 3750 3937 2984    0    0 2437
 3468 3581 2387    0    0 2085 3150 3174 1987    0    0 1830 2826 2790
 1691    0    0 1621 2515 2446 1457    0    0 1439 2228 2144 1264    0
    0 1276 1969 1880 1102    0    0 1130 1737 1649  963    0    0  999
 1530 1447  843    0    0  882 1347 1271  739    0    0  777 1185 1116
  648    0    0  684 1042  980  569    0    0  602  916  861  499    0
    0  530  805  756  438    0    0  466  708  664  385    0    0  410
  622  583  338    0    0  360  546  512  297    0    0  316  480  450
  261    0    0  278  422  395  229    0    0  244  370  347  201    0
    0  214  325  305  176    0    0  188  285  267  154    0    0  165
  250  234  135    0    0  145  219  205  118    0    0  127  192  180
  104    0    0  111  168  158   91    0    0   97  147  138   80    0
    0   85  129  121   70    0    0   74  113  106   61    0    0   65
   99   93   53    0    0   57   87   81   46    0    0   50   76   71
   40 

**EVALUACIÓN DE LA ECUACIÓN DE LA DIFUSIVIDAD EN FUNCIÓN 
DE LA PRESIÓN CON 10 CELDAS Y UN DT=5050 DÍAS**

In [ ]:
import numpy as np
L=1000 #distancia total
dx=100 #deltax
Distance=np.arange(0,L+1,dx) #Crear un vector de las distancias
P01=np.ones_like(Distance)
print (P01)

[1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
PYac=4000
PFrontd=0 #Frontera Derecha
PFronti=0 #Frontera Izquierda
Tiempo=288000
DT=5050
Pdt=np.zeros_like(Distance)

In [ ]:
P01=np.ones_like(Distance)
P01=P01*PYac
P01[0]=PFronti
P01[len(P01)-1]=PFrontd
P0in=P01 #Condicion inicial
Pdt=P01 #Vector de resultados DT
t=DT #Primera interaccion

In [ ]:
print (P01)

[   0 4000 4000 4000 4000 4000 4000 4000 4000 4000    0]


In [ ]:
def Presdt(P1,P2,P3,deltat,deltax):
  return(((P1-2*P2+P3)/(deltax*deltax))*deltat)+P2

In [ ]:
while t<Tiempo:
    for i in range(0,len(P0in)-1):
      if i==0:
        Pdt[i]=P0in[0]
      elif i==len(P0in)-1:
        Pdt[i]=P0in[len(P0in)-1]
      else:
        Pdt[i]=Presdt(P0in[i-1],P0in[i],P0in[i+1],DT,dx)
    t=t+DT
    P0in=Pdt
    P01=np.append(P01,Pdt)

In [ ]:
print (P01)

[   0 1980 2979 3484 3739 3868 3933 3966 3982 1970    0    0 1980 2979
 3484 3739 3868 3933 3966 3982 1970    0    0 1484 2479 3105 3483 3706
 3835 3907 2928 1458    0    0 1237 2167 2822 3261 3546 3725 3320 2383
 1188    0    0 1081 1949 2602 3072 3397 3354 2863 2021 1008    0    0
  973 1785 2426 2909 3128 2991 2502 1752  874    0    0  891 1657 2281
 2702 2843 2669 2207 1538  767    0    0  827 1552 2125 2481 2572 2386
 1959 1361  679    0    0  775 1448 1962 2264 2322 2138 1747 1211  604
    0    0  723 1341 1800 2058 2095 1918 1562 1081  539    0    0  669
 1233 1643 1867 1890 1724 1400  968  483    0    0  615 1127 1495 1690
 1705 1550 1257  869  434    0    0  562 1027 1357 1529 1537 1395 1130
  781  390    0    0  513  934 1230 1382 1387 1257 1017  702  350    0
    0  466  847 1113 1248 1251 1132  916  632  315    0    0  423  767
 1006 1127 1128 1020  825  569  284    0    0  383  693  909 1017 1017
  920  743  512  255    0    0  346  626  820  917  917  829  669  461
  230 

E